import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import staffRouter from "./staff";
import storefrontRouter from "./storefront";
import paymentsRouter from "./payments";
import shippingRouter from "./shipping";
import shippingRulesRouter from "./shipping-rules";
import notificationsRouter from "./notifications";
import tenantsRouter from "./tenants";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import customersRouter from "./customers";
import ordersRouter from "./orders";
import dashboardRouter from "./dashboard";
import onboardingRouter from "./onboarding";
import plansRouter from "./plans";
import platformRouter from "./platform";
import whatsappRouter from "./whatsapp";
import automationRouter from "./automation";
import followUpRouter from "./follow-up";
import returnsRouter from "./returns";
import stockLogsRouter from "./stock-logs";
import analyticsRouter from "./analytics";
import paymobRouter from "./paymob";
import billingRouter from "./billing";
import domainsRouter from "./domains";
import trackingRouter from "./tracking";
import exportsRouter from "./exports";
import auditRouter from "./audit";
import storeSettingsRouter from "./store-settings";
import uploadsRouter from "./uploads";
import discountsRouter from "./discounts";
import reviewsRouter from "./reviews";
import abandonedCartsRouter from "./abandoned-carts";
import inventoryAlertsRouter from "./inventory-alerts";
import aiImportRouter from "./ai-import";
import aiAssistantRouter from "./ai-assistant";
import facebookModeratorRouter from "./facebook-moderator";
import affiliatesRouter from "./affiliates";
import seoRouter from "./seo";
import egyptRouter from "./egypt";
import privacyRouter from "./privacy";

// Subscription enforcement is built into requireRole() in require-role.ts —
// every route that calls requireRole() automatically checks the tenant's subscription status.
// Public/storefront/platform-admin/billing routes are unaffected.

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(staffRouter);
router.use(storefrontRouter);
router.use(paymentsRouter);
router.use(shippingRouter);
router.use(shippingRulesRouter);
router.use(notificationsRouter);
router.use(tenantsRouter);
router.use(categoriesRouter);
router.use(productsRouter);
router.use(customersRouter);
router.use(ordersRouter);
router.use(dashboardRouter);
router.use(onboardingRouter);
router.use(plansRouter);
router.use(platformRouter);
router.use(whatsappRouter);
router.use(automationRouter);
router.use(followUpRouter);
router.use(returnsRouter);
router.use(stockLogsRouter);
router.use(analyticsRouter);
router.use(paymobRouter);
router.use(billingRouter);
router.use(domainsRouter);
router.use(trackingRouter);
router.use(exportsRouter);
router.use(auditRouter);
router.use(storeSettingsRouter);
router.use(uploadsRouter);
router.use(discountsRouter);
router.use(reviewsRouter);
router.use(abandonedCartsRouter);
router.use(inventoryAlertsRouter);
router.use(aiImportRouter);
router.use(aiAssistantRouter);
router.use(facebookModeratorRouter);
router.use(affiliatesRouter);
router.use(seoRouter);
router.use(egyptRouter);
router.use(privacyRouter);

export default router;
